export const scenes = {
  study0: {
    type: "text",
    text: "내일 드디어 하나금융TI 최종 면접이다! \n 면접 준비를 더 할까, 쉴까?",
    background: "url(../assets/study.webp)",
    next: "study1",
  },
  study1: {
    type: "text",
    text: "(따르르릉)",
    background: "url(../assets/study.webp)",
    next: "study2",
    sound: "../assets/sound/bell.mp3",
  },
  study2: {
    type: "text",
    text: "누구지? 이 시간에 전화 올 사람이 없는데.... (딸각)",
    background: "url(../assets/study.webp)",
    next: "study3",
  },
  study3: {
    type: "text",
    text: "???: 나 고민이 있는데 혹시 들어줄 수 있어...?",
    background: "url(../assets/study.webp)",
    next: "study4",
  },
  study4: {
    type: "text",
    text: "면접까지 12시간 남은 시각 \n 가장 친한 친구가 고민을 들어달라 한다... 어떻게 할까?",
    background: "url(../assets/study.webp)",
    next: "study_choice",
  },
  study_choice: {
    type: "choice",
    choices: [
      {
        text: "그래도 내일이 면접인데.. 면접 준비를 더 하다 잔다",
        next: "study_choice0",
        score: { 열정: 10, 존중과배려: -5 },
      },
      {
        text: "친구가 최고지! 친구 고민상담 들어준다",
        next: "study_choice1",
        score: { 존중과배려: 5, 열린마음: 10, 손님우선: 5 },
      },
      {
        text: "아 몰라... 그냥 쉰다",
        next: "study_choice2",
        score: { 열정: -5, 존중과배려: -5 },
      },
    ],
  },
  study_choice0: {
    type: "text",
    text: "좀 정리가 되는 것 같아",
    background: "url('../assets/study_more.png')",
    next: "Alarm",
  },
  study_choice1: {
    type: "text",
    text: "친구: 아니 글쎄 여자친구가 .... ....",
    background: "url(../assets/friend.webp)",
    next: "Alarm",
  },
  study_choice2: {
    type: "text",
    text: "잠도 안오는데 유튜브나 봐야겠다 ~",
    background: "url(../assets/rest.png)",
    next: "Alarm"
  },
  wakeUp0: {
    type: "text",
    text: "하아아아아암...",
    background: "url(../assets/wake_up.png)",
    next: "wakeUp1",
    sound: "../assets/sound/yawn.mp3",
  },
  wakeUp1: {
    type: "text",
    text: "7시에 일어났더니 피곤하네. \n 면접까지는 좀 시간이 남았는데 10분만 더 잘까?",
    background: "url(../assets/wake_up.png)",
    next: "wakeUp_choice",
    sound: null
  },
  wakeUp_choice: {
    type: "choice",
    choices: [
      {
        text: "잠깐은 괜찮겠지... 다시 눕는다.",
        next: "wakeUp_choice0",
        score: { 열정: -10 },
      },
      {
        text: "일찍 일어난 김에 빨리 씻자! 정신을 부여잡고 씻으러 간다.",
        next: "wakeUp_choice1",
        score: { 열정: 10 },
      },
    ],
  },
  wakeUp_choice0: {
    type: "text",
    text: "으악! 10분만 잔다는 게 그만... \n 늦었다! 얼른 일어나서 씻어야지!!",
    background: "url(../assets/late.png)",
    next: "dress0",
  },
  wakeUp_choice1: {
    type: "text",
    text: "부지런히 준비하니 여유롭고 좋아~ ♩♪♬",
    background: "url(../assets/breakfast.png)",
    next: "dress0",
  },
  dress0: {
    type: "text",
    text: "음 면접에는 어떤 옷을 입고 가야 될까?",
    background: "url(../assets/dress.png)",
    next: "dress_choice",
  },
  dress_choice: {
    type: "choice",
    choices: [{ text: "옷장을 연다.", next: "dressUp", score: {} }],
  },
  start: {
    type: "text",
    text: "... ... ... ... ...",
    background: "url('../assets/img_transport.webp')",
    next: "start1",
  },
  start0: {
    type: "text",
    text: "",
    background: "url('../assets/img_transport.webp')",
    next: "start1",
    sound: "../assets/sound/transport.wav",
  },
  start1: {
    type: "text",
    text: "면접장까지 1시간 반... 이번에 새로 생긴 버스가 빠르다고 한다. \n 새롭게 도전해볼까?",
    background: "url('../assets/img_transport.webp')",
    next: "start_choice",
    sound: "../assets/sound/transport.wav",
  },
  start_choice: {
    type: "choice",
    choices: [
      {
        text: "검증되지 않은 노선은 좀.. 안전하게 지하철 타고 가기",
        next: "subway0",
        score: { 전문성: 5, 존중과배려: 10 },
      },
      {
        text: "30분이나 빠르다고?! 새로 생긴 버스 타고 가기",
        next: "bus0",
        score: { 열린마음: 15 },
      },
    ],
  },
  subway0: {
    type: "text",
    text: "",
    background: "url('../assets/img_subway.webp')",
    next: "subway",
  },
  subway: {
    type: "text",
    text: "",
    background: "url('../assets/img_subway.webp')",
    next: "subway1",
    sound: "../assets/sound/subway.mp3",
  },
  subway1: {
    type: "text",
    text: "안내 방송 : 아- 아.... 현재 차량 고장으로 인해.. 열차가 지연 운행 되고 있습니다....",
    background: "url('../assets/img_subway.webp')",
    next: "subway2",
  },
  subway2: {
    type: "text",
    text: "뭐라고?! 큰일 났다.... 빨리 버스를 타러 가야해 !!",
    background: "url('../assets/img_subway.webp')",
    next: "bus",
  },
  bus0: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus.webp')",
    next: "bus",
  },
  bus: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus.webp')",
    next: "bus1",
    sound: null,
  },
  bus1: {
    type: "text",
    text: "새로 생겼다더니 좌석도 너무 편안하고 빨라서 좋다 ~~",
    background: "url('../assets/img_bus.webp')",
    next: "bus2",
  },
  nude: {
    type: "text",
    text: "???: 예끼 이놈아! 공공장소에 누가 그런 차림으로 다녀?! \n 당장 나가!!",
    background: "url('../assets/img_nude.png')",
    next: "fail_nude2",
    sound: null,
  },
  bus2: {
    type: "text",
    text: "버스를 타고 가는데, 할머니 한 분이 큰 짐을 들고 타셨다....",
    background: "url('../assets/img_bus_grandmother.webp')",
    next: "bus3",
    sound: "../assets/sound/bus.wav",
  },
  bus3: {
    type: "text",
    text: "어제 잠을 많이 못자서 피곤하긴 한데...\n자리를 양보해 드릴까?",
    background: "url('../assets/img_bus_grandmother.webp')",
    next: "bus4",
    sound: null,
  },
  bus4: {
    type: "choice",
    choices: [
      {
        text: "마음이 안좋아.. 자리를 양보한다.",
        next: "bus_good0",
        score: { 열린마음: 5, 존중과배려: 15, 손님우선: 15 },
      },
      {
        text: "좋은 컨디션으로 면접 봐야지.. 모르는 척 한다.",
        next: "bus_bad0",
        score: { 존중과배려: 1 },
      },
    ],
  },
  bus_good0: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus_good.webp')",
    next: "bus_good",
  },
  bus_good: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus_good.webp')",
    next: "bus_good1",
  },
  bus_good1: {
    type: "text",
    text: "큰 짐을 든 할머니: 아이고 정말 고마워요 ...! 복 받을 거야 !!",
    background: "url('../assets/img_bus_good.webp')",
    next: "bus_good2",
  },
  bus_good2: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus_good.webp')",
    next: "hana",
  },
  bus_bad0: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus_good.webp')",
    next: "bus_bad",
  },
  bus_bad: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus_good.webp')",
    next: "bus_bad1",
  },
  bus_bad1: {
    type: "text",
    text: "Zzzzz....",
    background: "url('../assets/img_bus_bad.webp')",
    next: "bus_bad2",
    sound: "../assets/sound/sleep.wav",
  },
  bus_bad2: {
    type: "text",
    text: "",
    background: "url('../assets/img_bus_bad.webp')",
    next: "hana",
    sound: null,
  },
  hana: {
    type: "text",
    text: "... ... ... ... ...",
    background: "url('../assets/img_hana.png')",
    next: "hana1",
  },
  hana1: {
    type: "text",
    text: "휴 드디어 도착했다.\n건물이 너무 멋지잖아?! 꼭 합격하고 말거야 !!",
    background: "url('../assets/img_hana.png')",
    next: "interview0",
  },
  interview0: {
    type: "text",
    text: "",
    background: "url('../assets/img_waiting.webp')",
    next: "interview1",
  },
  interview1: {
    type: "text",
    text: "면접관: 안녕하세요. 하나 금융 티아이 최종 면접 시작하겠습니다.",
    background: "url('../assets/img_interview.webp')",
    next: "interview2",
  },
  interview2: {
    type: "text",
    text: "면접관: (면접 복장에 따른 질문) 굉장히 편한 복장이네요. 회사에서도 자유로운 분위기를 선호하시는 편인가요?",
    background: "url('../assets/img_interview.webp')",
    next: "interview3",
  },
  interview3: {
    type: "text",
    text: "..... ..... ..... ..... ..... .....",
    background: "url('../assets/img_interview.webp')",
    next: "interview4",
  },
  interview4: {
    type: "text",
    text: "면접관: 네, 이상으로 면접 모두 마치겠습니다. 혹시 마지막으로 하시고 싶은 말씀 있으실까요?",
    background: "url('../assets/img_interview.webp')",
    next: "interview5",
  },
  interview5: {
    type: "choice",
    choices: [
      {
        text: "아까 미쳐 제대로 답변하지 못한 질문에 대한 보완을 하자!",
        next: "interview_good0",
        score: { 열정: 10, 전문성: 10 },
      },
      {
        text: "면접도 망한 것 같은데, 빨리 끝내고 싶어...\n최종 인사로 마무리 하자.",
        next: "interview_bad0",
        score: { 전문성: 0 },
      },
    ],
  },
  interview_good0: {
    type: "text",
    text: "",
    background: "url('../assets/img_interview.webp')",
    next: "interview_good",
  },
  interview_good: {
    type: "text",
    text: "",
    background: "url('../assets/img_interview.webp')",
    next: "interview_good1",
  },
  interview_good1: {
    type: "text",
    text: "아까 제가 했던 답변을 추가 보완해도 괜찮을 까요?\n... ... ...",
    background: "url('../assets/img_interview.webp')",
    next: "mail1",
  },
  interview_bad0: {
    type: "text",
    text: "",
    background: "url('../assets/img_interview.webp')",
    next: "interview_bad",
  },
  interview_bad: {
    type: "text",
    text: "",
    background: "url('../assets/img_interview.webp')",
    next: "interview_bad1",
  },
  interview_bad1: {
    type: "text",
    text: "뽑아주시면 열심히 하겠습니다 !",
    background: "url('../assets/img_interview.webp')",
    next: "mail1",
  },
  mail1: {
    type: "text",
    text: "띠리링 -",
    background: "url('../assets/img_mail.webp')",
    next: "mail2",
    sound: "../assets/sound/mail.mp3",
  },
  mail2: {
    type: "text",
    text: "헉 결과 메일이잖아? 얼른 확인해야지",
    background: "url('../assets/img_mail.webp')",
    next: "mail3",
    sound: null,
  },
  mail3: {
    type: "text",
    text: "헉 결과 메일이잖아? 얼른 확인해야지",
    background: "url('../assets/img_mail.webp')",
    next: null,
  },
  success1: {
    type: "text",
    text: "",
    background: "url('../assets/img_mail_success.png')",
    next: "success2",
  },
  success2: {
    type: "text",
    text: "야호 최종 합격이다!!!!!!!!!!!!!!!",
    background: "url('../assets/img_happy.png')",
    next: "success3",
  },
  success3: {
    type: "text",
    text: "",
    background: "url('../assets/img_happy.png')",
    next: null,
  },
  fail1: {
    type: "text",
    text: "",
    background: "url('../assets/img_mail_fail.png')",
    next: "fail2",
  },
  fail2: {
    type: "text",
    text: ".... .... ....",
    background: "url('../assets/img_sad.png')",
    next: "fail3",
  },
  fail3: {
    type: "text",
    text: "또 떨어졌잖아 .... ....",
    background: "url('../assets/img_sad.png')",
    next: "fail4",
  },
  fail4: {
    type: "text",
    text: "",
    background: "url('../assets/img_sad.png')",
    next: null,
  },
  fail_nude: {
    type: "text",
    text: "",
    background: "url('../assets/img_mail_fail.png')",
    next: "fail_nude2",
  },
  fail_nude2: {
    type: "text",
    text: ".... .... ....",
    background: "url('../assets/img_sad.png')",
    next: "fail_nude3",
  },
  fail_nude3: {
    type: "text",
    text: "옷차림 때문에 지각해서 면접 응시를 못하다니....",
    background: "url('../assets/img_sad.png')",
    next: "fail_nude4",
  },
  fail_nude4: {
    type: "text",
    text: "",
    background: "url('../assets/img_sad.png')",
    next: null,
  },
};
